name: socially
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Dart
  intl: ^0.19.0
  path: 1.9.0
  async: ^2.11.0
  collection: 1.18.0
  mime: ^2.0.0
  http: ^1.2.2

  # Flutter
  go_router: ^14.3.0
  path_provider: ^2.1.4
  cross_file: ^0.3.4+2
  url_launcher: ^6.3.1
  flutter_markdown: ^0.7.4+1

  # Flutter Community
  device_info_plus: ^11.1.0

  # 3rd Party
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5

  photo_view: ^0.15.0
  flutter_svg: ^2.0.10+1
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.4.1
  boxy: ^2.2.0

  google_fonts: ^6.2.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.4
  cloud_firestore: ^5.4.4
  timeago: ^3.7.0
  image: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13

  flutter_lints: ^5.0.0

  bloc_test: ^9.1.7

  flutter_gen_runner: ^5.8.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/svg/
    - assets/jpg/