// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNQ0Puce_EEy2yfuZFu1IlDgJW5uLNa2M',
    appId: '1:665751051618:web:4b2f5b74df6db4dbdba03b',
    messagingSenderId: '665751051618',
    projectId: 'socially-63f17',
    authDomain: 'socially-63f17.firebaseapp.com',
    storageBucket: 'socially-63f17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo-VeZ54R8NxYzO5ZkxUA3MDps0VTva_8',
    appId: '1:665751051618:android:202191b056d757d2dba03b',
    messagingSenderId: '665751051618',
    projectId: 'socially-63f17',
    storageBucket: 'socially-63f17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi8sROEkip6L2xnnkD_xsEze2hFp9RXJY',
    appId: '1:665751051618:ios:d7381ce0471b1c02dba03b',
    messagingSenderId: '665751051618',
    projectId: 'socially-63f17',
    storageBucket: 'socially-63f17.appspot.com',
    iosBundleId: 'net.inferno.socially',
  );
}
